// GENERATED by scripts/train-ml-model.ts — do not edit by hand. Re-run the script to retrain.
import type { MlModel } from "../domain/ml-features";

export const ML_WEIGHTS: MlModel = {
  "weights": [
    0.725218,
    0.331361,
    0.425052,
    0.295081,
    0.558001,
    0.653425,
    1.332154,
    1.236858,
    0.589088,
    0.694914,
    0.658084,
    0.534805,
    0.794062,
    1.513708
  ],
  "bias": -3.857304,
  "featureNames": [
    "velocity.attemptsLast2m",
    "velocity.attemptsLast24h",
    "velocity.amountLast1h",
    "device.firstSeen",
    "device.usersOnDevice",
    "device.usersOnFingerprint",
    "device.fingerprintDeviceMismatch",
    "geo.impossibleTravel",
    "geo.countryChanged",
    "geo.ipSimMismatch",
    "graph.ringSize",
    "graph.usersOnIp",
    "anomaly.amountZScore",
    "rules.score"
  ],
  "trainedAt": "2026-09-23",
  "metrics": {
    "auc": 0.843296,
    "accuracy": 0.87275,
    "samples": 20000
  }
};
