/**
 * Offline trainer for the ML risk scorer. It generates a synthetic, labelled dataset, fits a
 * logistic-regression model with gradient descent (pure TS, no deps), evaluates it on a holdout,
 * and writes the weights to src/contexts/scoring/model/ml-weights.ts. The engine never trains at
 * runtime — it loads these weights and serves an O(features) dot-product, so inference is fast and
 * the decision path is untouched. Re-run with: npx tsx scripts/train-ml-model.ts
 *
 * The feature order MUST match ML_FEATURE_NAMES in src/contexts/scoring/domain/ml-features.ts.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const FEATURE_NAMES = [
  "velocity.attemptsLast2m",
  "velocity.attemptsLast24h",
  "velocity.amountLast1h",
  "device.firstSeen",
  "device.usersOnDevice",
  "device.usersOnFingerprint",
  "device.fingerprintDeviceMismatch",
  "geo.impossibleTravel",
  "geo.countryChanged",
  "geo.ipSimMismatch",
  "graph.ringSize",
  "graph.usersOnIp",
  "anomaly.amountZScore",
  "rules.score",
];
const D = FEATURE_NAMES.length;

// A small seeded PRNG (mulberry32) so training is reproducible and the committed weights are stable.
function rng(seed: number): () => number {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const sigmoid = (z: number): number => 1 / (1 + Math.exp(-z));

// The synthetic "ground truth": how the world decides fraud, in scaled feature space. The trained
// model should recover a similar shape. Signs match intuition (spoofing/impossible-travel raise risk).
const TRUE_W = [1.5, 0.8, 1.0, 0.6, 1.2, 1.3, 2.0, 2.2, 0.9, 1.1, 1.4, 1.0, 1.6, 2.5];
const TRUE_B = -6.2;

function sample(rand: () => number): { x: number[]; y: number } {
  const skewed = () => rand() ** 3; // most values low, a long tail high — like real risk features
  const binary = (p: number) => (rand() < p ? 1 : 0);
  const x = [
    skewed(), skewed(), skewed(), // velocity
    binary(0.3), skewed(), skewed(), binary(0.08), // device / fingerprint
    binary(0.05), binary(0.15), binary(0.1), // geo
    skewed(), skewed(), // graph
    skewed(), skewed(), // anomaly z-score, rule score
  ];
  const noise = (rand() - 0.5) * 1.2;
  const logit = TRUE_B + noise + x.reduce((s, xi, i) => s + xi * TRUE_W[i], 0);
  return { x, y: rand() < sigmoid(logit) ? 1 : 0 };
}

function train(data: { x: number[]; y: number }[], epochs: number, lr: number, l2: number): { w: number[]; b: number } {
  let w = new Array(D).fill(0);
  let b = 0;
  for (let e = 0; e < epochs; e++) {
    const gw = new Array(D).fill(0);
    let gb = 0;
    for (const { x, y } of data) {
      const p = sigmoid(b + x.reduce((s, xi, i) => s + xi * w[i], 0));
      const d = p - y;
      for (let i = 0; i < D; i++) gw[i] += d * x[i];
      gb += d;
    }
    const n = data.length;
    for (let i = 0; i < D; i++) w[i] -= lr * (gw[i] / n + l2 * w[i]);
    b -= lr * (gb / n);
  }
  return { w, b };
}

function evaluate(model: { w: number[]; b: number }, data: { x: number[]; y: number }[]): { auc: number; accuracy: number } {
  const scored = data.map(({ x, y }) => ({ p: sigmoid(model.b + x.reduce((s, xi, i) => s + xi * model.w[i], 0)), y }));
  const correct = scored.filter((s) => (s.p >= 0.5 ? 1 : 0) === s.y).length;
  // AUC via the rank-sum (Mann–Whitney) identity.
  const pos = scored.filter((s) => s.y === 1);
  const neg = scored.filter((s) => s.y === 0);
  let wins = 0;
  for (const p of pos) for (const n of neg) wins += p.p > n.p ? 1 : p.p === n.p ? 0.5 : 0;
  const auc = pos.length && neg.length ? wins / (pos.length * neg.length) : 0.5;
  return { auc, accuracy: correct / data.length };
}

function main(): void {
  const rand = rng(42);
  const all = Array.from({ length: 20_000 }, () => sample(rand));
  const split = Math.floor(all.length * 0.8);
  const trainSet = all.slice(0, split);
  const testSet = all.slice(split);

  const model = train(trainSet, 400, 0.5, 1e-4);
  const metrics = evaluate(model, testSet);
  const fraudRate = all.filter((d) => d.y === 1).length / all.length;

  const round = (n: number): number => Math.round(n * 1e6) / 1e6;
  const out = {
    weights: model.w.map(round),
    bias: round(model.b),
    featureNames: FEATURE_NAMES,
    trainedAt: new Date().toISOString().slice(0, 10),
    metrics: { auc: round(metrics.auc), accuracy: round(metrics.accuracy), samples: all.length },
  };

  const file = join(__dirname, "..", "src", "contexts", "scoring", "model", "ml-weights.ts");
  const banner =
    "// GENERATED by scripts/train-ml-model.ts — do not edit by hand. Re-run the script to retrain.\n" +
    "import type { MlModel } from \"../domain/ml-features\";\n\n";
  writeFileSync(file, `${banner}export const ML_WEIGHTS: MlModel = ${JSON.stringify(out, null, 2)};\n`);

  // eslint-disable-next-line no-console
  console.log(`Trained on ${all.length} synthetic samples (fraud rate ${(fraudRate * 100).toFixed(1)}%).`);
  // eslint-disable-next-line no-console
  console.log(`Holdout AUC ${metrics.auc.toFixed(3)}, accuracy ${(metrics.accuracy * 100).toFixed(1)}%. Wrote ${file}`);
}

main();
